import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Session } from "next-auth";
import ReactQuery from "@/components/ReactQuery";
import NextAuthProvider from "@/components/NextAuthProvider";

interface NextAuthProps {
  children: React.ReactNode;
  session: Session | null | undefined;
}

const quciksand = localFont({
  src: [
    {
      path: "../public/fonts/Quicksand-Light.ttf",
      weight: "300",
      style: "light",
    },
    {
      path: "../public/fonts/Quicksand-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Quicksand-Medium.ttf",
      weight: "500",
      style: "medium",
    },
    {
      path: "../public/fonts/Quicksand-SemiBold.ttf",
      weight: "600",
      style: "semibold",
    },
    {
      path: "../public/fonts/Quicksand-Bold.ttf",
      weight: "700",
      style: "bold",
    },
  ],
});

export const metadata: Metadata = {
  title: "Next JS",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }: NextAuthProps) {
  return (
    <html lang="en">
      <body className={quciksand.className}>
        <NextAuthProvider session={session}>
          <ReactQuery>{children}</ReactQuery>
        </NextAuthProvider>
      </body>
    </html>
  );
}
